remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme 

title: [Anu]
description: [Your always-ready, on-demand AI assistant.]
show_downloads: [true]

include:
  - publish
  - changelogs

