name: macos-release

on:
  push:
    tags:
      - 'v*'

jobs:
  macos-release:
    if : ${{ startsWith(github.ref, 'refs/tags/') }}
    strategy:
      matrix:
        cpu: [x64, arm64]

    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup software form homebrew
        run: |
          export HOMEBREW_NO_AUTO_UPDATE=true
          brew install create-dmg

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x

      - name: Install dotnet workload and dependencies
        working-directory: ./src/Anu.Desktop.MacOS
        run: |
          dotnet workload restore
          dotnet restore

      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 16.*
          
      - name: Build ${{ matrix.cpu }}
        run: |
          dotnet publish Anu.Desktop.MacOS.csproj -r osx-${{ matrix.cpu }} -c Release
        working-directory: ./src/Anu.Desktop.MacOS

      - name: Get Tag Name
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - name: Package dmg
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 15
          max_attempts: 5
          warning_on_retry: false
          retry_on: error
          command: |
            cd ./src/Anu.Desktop.MacOS/bin/Release/net9.0-macos/osx-${{ matrix.cpu }}/
            create-dmg --volname "Anu Installer" \
             --volicon "AppIcon.icns" \
             --window-pos 200 120 \
             --window-size 550 330 \
             --icon-size 100 \
             --icon "Anu.app" 150 140 \
             --hide-extension "Anu.app" \
             --app-drop-link 400 140 \
             "Anu-Installer.dmg" \
             "Anu.app"

      - name: Change name
        run: mv Anu-Installer.dmg "Anu-${{ env.TAG_NAME }}-macos-${{ matrix.cpu }}.dmg"
        working-directory: ./src/Anu.Desktop.MacOS/bin/Release/net9.0-macos/osx-${{ matrix.cpu }}/

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          prerelease: ${{ contains(github.ref_name, 'beta') }}
          artifacts: ./src/Anu.Desktop.MacOS/bin/Release/net9.0-macos/osx-${{ matrix.cpu }}/Anu-${{ env.TAG_NAME }}-macos-${{ matrix.cpu }}.dmg
